name: Abertura de tarefa
description: Abrir uma tarefa para em caso de problema, correção ou sugestão
title: "[Correcao] "
labels: ["problema", "correção", "sugestão"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sua contribuição!
        Se chegou até aqui terá sua primeira chance de contribuir para este repositório:
        - Se clicou em algum link dos conteudos, provavelmente encontrou algum link sem referencia!
          * Você pode procurar um link legal para preencher este espaço.
          * Você pode sinalizar, caso ninguem tenha sinalizado antes.
        - Se encontrou algum problema, ou deseja sugerir uma correção
  - type: dropdown
    id: subject
    attributes:
      label: "Como chegou aqui?"
      description: "Entrou intencionalmente, ou estava tentando acessar um link de referencia do conteudo."
      options:
        - "Encontrei um link nos meio do conteudo que me mandou aqui!"
        - "Entrei na intenção de abrir uma issue!"
    validations:
      required: true
  - type: dropdown
    id: help
    attributes:
      label: "Como quer ajudar?"
      description: "Como pretende ajudar abrindo essa issue."
      options:
        - "Apenas sinalizar um link que jogou aqui"
        - "Quero sugerir um link para um link que joga aqui"
        - "Achei um erro no conteudo"
        - "Achei um erro de português"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Descreva qual o problema, ou como ajudar"
      description: "Explique o problema que encontrou, ou sugira uma mudança."
      placeholder: "Quero sugerir esse link: https://xpto.com para o conteudo /como-a-web-funciona.md!"
    validations:
      required: true
